CREATE DATABASE KUHUMUN;
USE KUHUMUN;
/*
CREATE TABLE INFO_COLLECT(
	INFO_ID int(11) NOT NULL AUTO_INCREMENT,
	USER_IP char(20) NOT NULL,
	RES_TITLE char(20) NOT NULL,
	RES_CONTENT char(200) NOT NULL,
	INPUT_TIME time() DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (INFO_ID)
); 
*/
CREATE TABLE RESTAURANT(
	RES_ID int(5) NOT NULL AUTO_INCREMENT,
	RES_TITLE char(20) NOT NULL,
	PRIMARY KEY (RES_ID)
);


CREATE TABLE RES_DETAIL(
	DETAIL_ID int(5) NOT NULL,
	RES_ID int(5) NOT NULL,
	RES_MENU char(15) NOT NULL,
	RES_PRICE char(6) NOT NULL,
	USER_IP char(20) NOT NULL,
	INPUT_TIME time() DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY(DETAIL_ID)
);
