CREATE DATABASE KUHUMUN DEFAULT CHARACTER SET UTF8;
USE KUHUMUN;

CREATE TABLE RESTAURANT(
	RES_ID int(5) NOT NULL AUTO_INCREMENT,
	RES_TITLE char(20) NOT NULL,
	RES_SUBTITLE char(30) DEFAULT NULL,
	RES_MENU_SUBTITLES char(75) DEFAULT NULL,
	REPORT_COUNT tinyint(3) DEFAULT 0,
	PROVEN_CODE tinyint(1) DEFAULT 0,
	PRIMARY KEY (RES_ID),
	UNIQUE INDEX (RES_TITLE)
);


CREATE TABLE RES_DETAIL(
	DETAIL_ID int(5) NOT NULL AUTO_INCREMENT,
	RES_ID int(5) NOT NULL,
	RES_MENU char(29) NOT NULL,
	RES_MENU_CODE tinyint(1) DEFAULT 0,
	RES_PRICE int(6) NOT NULL,
	USER_IP char(20) NOT NULL,
	INPUT_TIME date NOT NULL,
	REPORT_COUNT tinyint(3) DEFAULT 0,
	PROVEN_CODE tinyint(1) DEFAULT 0,
	PRIMARY KEY(DETAIL_ID)
);

CREATE TABLE REPORT(
	RES_ID int(5) NOT NULL,
	DETAIL_ID int(5) NOT NULL,
	USER_IP char(20) NOT NULL,
	INPUT_TIME datetime NOT NULL,

	PRIMARY KEY(INPUT_TIME)
);


CREATE TABLE BLOCK_LIST(
	USER_IP char(20) NOT NULL,

	PRIMARY KEY(USER_IP)
);

CREATE TABLE COMMENT(
	COMMENT_ID int(7) NOT NULL AUTO_INCREMENT,
	RES_ID int(5) NOT NULL,
	COMMENT char(30) NOT NULL,
	USER_IP char(20) NOT NULL,
	INPUT_TIME datetime NOT NULL,

	PRIMARY KEY(COMMENT_ID)
);

CREATE TABLE IMG_REPORT(
	IMG_ID int(3) NOT NULL AUTO_INCREMENT,
	RES_TITLE char(20) NOT NULL,
	RES_menu char(20) DEFAULT NULL,
	IMG_NAME text NOT NULL,
	USER_IP char(20) NOT NULL,
	INPUT_TIME datetime NOT NULL,

	PRIMARY KEY(IMG_ID)
);

CREATE TABLE RES_TYPE(
	TYPE_ID tinyint(3) NOT NULL,
	TYPE_NAME char(10) NOT NULL,
	RES_STRING text DEFAULT NULL,
	PRIMARY KEY(TYPE_ID)
);

CREATE TABLE RES_IMG(
	RES_IMG_ID int(3) NOT NULL AUTO_INCREMENT,
	RES_ID int(3) NOT NULL,
	RES_MENU char(20) NOT NULL,
	IMG_NAME text NOT NULL,
	PRIMARY KEY(RES_IMG_ID)
);